# Generated by Django 5.2 on 2026-06-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("setting_key", models.CharField(max_length=80, unique=True)),
                ("setting_value", models.TextField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "business_settings",
                "ordering": ["setting_key"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        help_text="E.164 format, e.g. +2348012345678",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=120, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "workflow_state",
                    models.CharField(
                        choices=[
                            ("NEW_LEAD", "New Lead"),
                            ("AWAITING_REPLY", "Awaiting Reply"),
                            ("INTERESTED", "Interested"),
                            ("PENDING_PAYMENT", "Pending Payment"),
                            ("PAID", "Paid"),
                            ("ESCALATED", "Escalated"),
                        ],
                        db_index=True,
                        default="NEW_LEAD",
                        max_length=20,
                    ),
                ),
                ("human_takeover", models.BooleanField(db_index=True, default=False)),
                (
                    "takeover_by",
                    models.CharField(
                        blank=True,
                        help_text="Admin username who took over the conversation",
                        max_length=120,
                        null=True,
                    ),
                ),
                ("follow_up_count", models.PositiveSmallIntegerField(default=0)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("WHATSAPP", "WhatsApp"), ("WEB_FORM", "Web Form")],
                        default="WHATSAPP",
                        max_length=10,
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, help_text="Flexible metadata", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "customers",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["last_message_at"], name="idx_last_message_at")
                ],
            },
        ),
    ]
