# Generated by Django 5.2 on 2026-06-11 13:03

from django.db import migrations


def seed_settings(apps, schema_editor):
    BusinessSetting = apps.get_model("customers", "BusinessSetting")
    settings = [
        BusinessSetting(
            setting_key="business_name",
            setting_value="My Business",
            description="Business display name used in messages"
        ),
        BusinessSetting(
            setting_key="support_phone",
            setting_value="+2348000000000",
            description="Human support WhatsApp number"
        ),
        BusinessSetting(
            setting_key="product_catalog",
            setting_value="{}",
            description="JSON blob of product names + prices"
        ),
        BusinessSetting(
            setting_key="ai_base_prompt",
            setting_value="You are a helpful Nigerian sales assistant. Be polite, friendly, and guide the customer to purchase.",
            description="Base LLM system prompt"
        )
    ]
    BusinessSetting.objects.bulk_create(settings)


def unseed_settings(apps, schema_editor):
    BusinessSetting = apps.get_model("customers", "BusinessSetting")
    BusinessSetting.objects.filter(
        setting_key__in=["business_name", "support_phone", "product_catalog", "ai_base_prompt"]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_settings, reverse_code=unseed_settings),
    ]

