# Generated by Django 5.2 on 2026-06-11 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_kobo",
                    models.PositiveIntegerField(
                        help_text="Amount in kobo (e.g., 500000 = ₦5,000)"
                    ),
                ),
                ("currency", models.CharField(default="NGN", max_length=3)),
                (
                    "paystack_reference",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "paystack_access_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("payment_url", models.URLField(blank=True, max_length=512, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("ABANDONED", "Abandoned"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("gateway_response", models.JSONField(blank=True, null=True)),
                ("reminder_count", models.PositiveSmallIntegerField(default=0)),
                ("last_reminder_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="orders",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
    ]
