# Generated by Django 5.2 on 2026-06-11 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("media_url", models.URLField(blank=True, max_length=512, null=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("INBOUND", "Inbound"), ("OUTBOUND", "Outbound")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[("USER", "User"), ("BOT", "Bot"), ("ADMIN", "Admin")],
                        max_length=10,
                    ),
                ),
                (
                    "detected_intent",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GREETING", "Greeting"),
                            ("PRODUCT_INQUIRY", "Product Inquiry"),
                            ("BUYING_INTENT", "Buying Intent"),
                            ("OBJECTION", "Objection"),
                            ("SUPPORT_OR_HUMAN", "Support / Human"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        db_index=True,
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "intent_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Confidence score from 0.000 to 1.000",
                        max_digits=4,
                        null=True,
                    ),
                ),
                ("twilio_sid", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "created_at"], name="idx_customer_created"
                    )
                ],
            },
        ),
    ]
